curl -X POST -H "Content-Type: application/json" -d '{"hello": "fe"}' http://localhost:8080/upload
###
curl -X POST -d '{"hello": "fe"}' http://localhost:8080/upload

//https://www.google.com/search?q=request+response+fastify&ie=UTF-8