POST http://localhost:3000/upload/dta
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="dta2.pdf"
Content-Type: application/pdf

< /data/input/dta2.pdf
--boundary--
